---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-database-zhangzhikai-com-cn-v1-mysql
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURDekNDQWZPZ0F3SUJBZ0lVT3g4Lys5a1FiSlhSK2hFOEwzaTBlNzVGTVE0d0RRWUpLb1pJaHZjTkFRRUwKQlFBd0ZURVRNQkVHQTFVRUF3d0tkMlZpYUc5dmF5MWpZVEFlRncweU5EQTRNRGN3TnpFd01qUmFGdzB6TkRBNApNRFV3TnpFd01qUmFNQlV4RXpBUkJnTlZCQU1NQ25kbFltaHZiMnN0WTJFd2dnRWlNQTBHQ1NxR1NJYjNEUUVCCkFRVUFBNElCRHdBd2dnRUtBb0lCQVFDMHZlNHVuOWpLbCtwWEJ4cHZKOTV1WGl1V3dJT2ltb2ZqSVN6aDg1cG4KRmJZeC9QM2VvN01vWldtRzZQZ0NmUzg5K055ZGhIbkhKMjlGeVNqT2lxNmhDeVlacm5uRlJocTBrT0l3bFN4ZQp2bWlLL1lFUERBSTBFRjRVM0pMbzd4cEFYV0lySjJlLytRNkhLMVROUUduUDFhZ09ISngyV29vMFBiYXpsa0E4ClJROStsWWduZTBibWdWdjFqNllveFJ6Q25YRW9LYUQwQ2U5M3Q3RXVjT3RZTkU0RTZmTjFUWUNRYTVobmdXZGEKaEZGcm1McXlNK2V3U0pYbFdMTUh0ZWJPd1dEUHZxeXB3dWRvQmpRZmVJR3hiUkt6cHhUS01xQndWUVhPZ3A0bQo1UFNDZFRqdEsyV1pNQ1BFNDNweXg1QnRKczdQcTE4L0E4Y211SGk5RFpPMUFnTUJBQUdqVXpCUk1CMEdBMVVkCkRnUVdCQlJsYlZ3aDRmb2dnQlhNeWxWMFlaeWx4RHkzTmpBZkJnTlZIU01FR0RBV2dCUmxiVndoNGZvZ2dCWE0KeWxWMFlaeWx4RHkzTmpBUEJnTlZIUk1CQWY4RUJUQURBUUgvTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFBYgo2ODU2RVJKd2ZSWWFzaWhhNmdpdncvcTAwSlN2cHFoSkh0eU5BYnNaMTJDaWpCVXVZTmdqYkwzb1lUWWtqZk9tCmFwY1VUSHFZRkIxRUZ2VHhDbWhxOHFuR1pMV1dVMnBIdXJwQW1aZk0zMERMZmRQL0E1ZTdSaXRSWFJHZU92d2cKZnY3ZlRWQUp0UDRFdlVTZDBKakZmd0VvUUh0d1VmNXdWQnU3U1RXVE90TmM5dE5IbThkUWtTcmY1SmpQZUh6bQpRREtVMVFvRURGcE1VLy9JbEhlYXpKcllSaTQ3SzBCSHh0QmpIK0dIdlNiR2ljL1NhUSszZ0kyekhoZU1KcDB6Cnc4aHlDTW8yc3NOdkRrWmlZZTVVMi9Iampmb2h5ZXNNd2x4U3o5L0dMRVhzb1doVTJPQXVocXI2WHl4OEptVjgKVWhJSXYzdERZR0VBRW4vUDBCdWkKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  failurePolicy: Fail
  name: vmysql.kb.io
  rules:
  - apiGroups:
    - database.zhangzhikai.com.cn
    apiVersions:
    - v1
    operations:
    - CREATE
    - UPDATE
    - DELETE
    resources:
    - mysqls
  sideEffects: None
