apiVersion: database.zhangzhikai.com.cn/v1
kind: MySQL
metadata:
  labels:
    app.kubernetes.io/name: myoperator
    app.kubernetes.io/managed-by: kustomize
  name: mysql-sample
spec:
  # TODO(user): Add fields here
