apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: myoperator-webhook
    control-plane: controller-manager-webhook
  name: myoperator-controller-manager-webhook
  namespace: myoperator-system
spec:
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      control-plane: controller-manager-webhook
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        control-plane: controller-manager-webhook
    spec:
      containers:
        - args:
            - --metrics-bind-address=:8443
            - --health-probe-bind-address=:8081
          command:
            - /manager
          image: your-registry/zhangzhikai-pub/operator/zzkoperator:202408072100
          imagePullPolicy: IfNotPresent
          env:
            - name: ENABLE_WEBHOOKS
              value: "true"
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 15
            periodSeconds: 20
            successThreshold: 1
            timeoutSeconds: 1
          name: manager-webhook
          ports:
            - containerPort: 9443
              name: webhook-server
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /readyz
              port: 8081
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 10m
              memory: 64Mi
          securityContext:
            allowPrivilegeEscalation: false
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /webhook/serving-certs
              name: cert
              readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        runAsNonRoot: true
      serviceAccount: myoperator-controller-manager
      serviceAccountName: myoperator-controller-manager
      terminationGracePeriodSeconds: 10
      volumes:
        - name: cert
          secret:
            defaultMode: 420
            secretName: webhook-tls